[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy-Report-Only = "default-src 'none'; script-src 'self' b24-zzv2y8.bitrix24.com cdn.bitrix24.com unpkg.com; style-src 'self' 'unsafe-inline' fonts.googleapis.com fonts.gstatic.com b24-zzv2y8.bitrix24.com cdnjs.cloudflare.com; font-src fonts.googleapis.com fonts.gstatic.com cdnjs.cloudflare.com; img-src 'self'; connect-src 'self' unpkg.com; base-uri 'self'; form-action 'self';"

[functions]
  directory = "functions"
